WIP: fix(render-table): add table component for target page
osu-cass/AP-CSE-APP pull request #108
Opened 2019-01-05 01:01 UTC by iglenwoo

# Changes introduced

I have added a table component for target page.

## Related issue(s):

- [CSE-391](https://sbacjira.atlassian.net/browse/CSE-391)

## Contributor checklist

- [ ] Wrote/updated tests for introduced changes
- [ ] Added new stories for created/modified components (if applicable)
- [ ] Checked Storybook for Accessibility issues (if applicable)
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [ ] Verified that there are no issues in CircleCI
- [ ] Assigned yourself to the PR
- [ ] Removed `WIP:` from the PR title
- [ ] Requested review from the SB Reviewers team

## Reviewer checklist

- [ ] Assigned yourself to the PR
- [ ] Read through the changes in the `Files changed` tab
- [ ] Verified that tests were written/modified
- [ ] Verified that stories were written/modified (if applicable)
- [ ] ~~Verified that Postman was updated (if applicable)~~
- [ ] Checked out the branch and tested changes locally
- [ ] Run storybook and checked that there are no accessibility issues

2019-01-14 20:04 UTC, puregarlic commented on src/components/TargetDetails/parseUtils.tsx
> +  const foundTables = text.match(grepTablesRegex);
1. Check if the content contains a table, and then call the correct parsing function.

2019-01-14 20:12 UTC, puregarlic commented on src/components/TargetDetails/parseUtils.tsx
> +  const parts = text.split(grepTablesRegex);
2. Capture first and last pipes, returning all of the table content.

2019-01-14 20:15 UTC, puregarlic commented on src/components/TargetDetails/parseUtils.tsx
> +    const tableMatched = part.match(grepTablesRegex);
```suggestion
    const containsTable = part.match(grepTablesRegex);
```

2019-01-14 20:15 UTC, puregarlic commented on src/components/TargetDetails/parseUtils.tsx
> +    if (tableMatched) {
```suggestion
    if (containsTable) {
```

2019-01-15 18:58 UTC, iglenwoo commented on src/components/TargetDetails/parseUtils.tsx
> +const parseTables = (lines: string[], underlined: boolean) => {
This function is complex since it contains parsing tables logics.
Please take a look at this and give me any feedback that I can improve this.

2019-01-25 21:25 UTC, danvanhorn commented on src/components/TargetDetails/parseUtils.tsx
> +    if (tableRow) {
I think we can merge the two ifs and get rid of the tableRow variable like this:
```
if(!lines.trim() && line.match(/\|.*\|/)) {
    ...
}
```

2019-01-25 21:27 UTC, danvanhorn commented on src/components/TargetDetails/parseUtils.tsx
> +  for (let index = lines.length - 1; index >= 0; index--) {
We probably dont have to use an old school for loop here, we can do:
```
return lines.reverse().map((line: string) => {
    const tableRow: React.ReactNode;
    ...
    return tableRow;
})
```
instead of returning the array at the end, you can edit the anonymous function passed into map to return a `ReactNode`. That means we can also remove the variable, `tablesWithStrngsJSX`

2019-01-25 21:35 UTC, danvanhorn requested changes
Check the comments I made on that function and try out that refactor, I think we can ignore the cognitive complexity.

2019-01-28 22:26 UTC, danvanhorn approved these changes

2019-01-28 22:27 UTC, merged

2019-01-28 22:29 UTC, cass-osu commented
:tada: This PR is included in version 1.34.1 :tada:

The release is available on [GitHub release](https://github.com/osu-cass/AP-CSE-APP/releases/tag/v1.34.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: