Fix/cse-422-content-nav-accessibility
osu-cass/AP-CSE-APP pull request #134
Opened 2019-01-18 21:05 UTC by Bensonre

- Updates content nav style to bold all nav items
- makes sub menu items black to match menu items.
- removes wrapping from sub menu items. 

## Related issue(s):

- CSE-422
- CSE-_task number_

## Contributor checklist

- [ ] Wrote/updated tests for introduced changes
- [ ] Added new stories for created/modified components (if applicable)
- [ ] Checked Storybook for Accessibility issues (if applicable)
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [ ] Verified that there are no issues in CircleCI
- [ ] Assigned yourself to the PR
- [ ] Removed `WIP:` from the PR title
- [ ] Requested review from the SB Reviewers team

## Reviewer checklist

- [ ] Assigned yourself to the PR
- [ ] Read through the changes in the `Files changed` tab
- [ ] Verified that tests were written/modified
- [ ] Verified that stories were written/modified (if applicable)
- [ ] ~~Verified that Postman was updated (if applicable)~~
- [ ] Checked out the branch and tested changes locally
- [ ] Run storybook and checked that there are no accessibility issues

2019-01-18 21:07 UTC, Bensonre commented
code climate just found similar CSS in 3 locations

2019-01-22 22:47 UTC, tnoelcke requested changes
Could you also please make the sub items bold? I think the fact that they are indented is probably enough to indicate that they are subitems. Thanks!

2019-01-25 00:00 UTC, tnoelcke approved these changes

2019-01-25 00:00 UTC, merged

2019-01-25 00:01 UTC, cass-osu commented
:tada: This PR is included in version 1.32.3 :tada:

The release is available on [GitHub release](https://github.com/osu-cass/AP-CSE-APP/releases/tag/v1.32.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: