Configure CodeClimate
osu-cass/AP-CSE-APP pull request #21
Opened 2018-10-09 22:22 UTC by puregarlic

# Changes introduced

This PR adds a configuration file for CodeClimate for better analysis of our code's technical debt.

## Contributor checklist

- [ ] Wrote/updated tests for introduced changes
- [ ] Added new stories for created/modified components (if applicable)
- [ ] Checked Storybook for Accessibility issues (if applicable)
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [x] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [x] Removed `WIP:` from the PR title
- [x] Requested review from the SB Reviewers team

## Reviewer checklist

- [ ] Assigned yourself to the PR
- [ ] Read through the changes in the `Files changed` tab
- [ ] Verified that tests were written/modified
- [ ] Verified that stories were written/modified (if applicable)
- [ ] ~~Verified that Postman was updated (if applicable)~~
- [ ] Checked out the branch and tested changes locally
- [ ] Run storybook and checked that there are no accessibility issues

2018-10-10 13:26 UTC, tnoelcke requested changes

2018-10-10 13:26 UTC, tnoelcke commented on .codeclimate.yml
> +      strings:
This doesn't seem right is there something wrong with the codeclimate.yaml configuration in general or should we be adding this as a technical debt issue?

2018-10-10 21:08 UTC, puregarlic commented on .codeclimate.yml
> +      strings:
No, this is the intended configuration. `fixme` is the name of a CodeClimate engine that identifies suspicious comments and raises them as technical debt issues.

2018-10-10 21:55 UTC, tnoelcke commented on .codeclimate.yml
> +      strings:
Ok Makes sense. I'll get this merged. Thanks!

2018-10-10 21:55 UTC, tnoelcke approved these changes

2018-10-10 21:56 UTC, merged

2018-11-09 01:05 UTC, cass-osu commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/osu-cass/AP-CSE-APP/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: