Feat/home page
osu-cass/AP-CSE-APP pull request #26
Opened 2018-10-26 14:13 UTC by MatthewArck

# Changes introduced

_describe changes here_

## Related issue(s):

- CSE-_user story or bug_
- CSE-_task number_

## Contributor checklist

- [ ] Wrote/updated tests for introduced changes
- [ ] Added new stories for created/modified components (if applicable)
- [ ] Checked Storybook for Accessibility issues (if applicable)
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [ ] Verified that there are no issues in CircleCI
- [ ] Assigned yourself to the PR
- [ ] Removed `WIP:` from the PR title
- [ ] Requested review from the SB Reviewers team

## Reviewer checklist

- [ ] Assigned yourself to the PR
- [ ] Read through the changes in the `Files changed` tab
- [ ] Verified that tests were written/modified
- [ ] Verified that stories were written/modified (if applicable)
- [ ] ~~Verified that Postman was updated (if applicable)~~
- [ ] Checked out the branch and tested changes locally
- [ ] Run storybook and checked that there are no accessibility issues

2018-10-26 17:57 UTC, tnoelcke requested changes
We need to remove the Coverage files and Reports directory form this PR. Those are in the git ignore and shouldn't have gotten checked in in the first place.

2018-11-02 00:43 UTC, danvanhorn commented on src/clients/search/index.ts
> +export class SearchClient implements ISearchClient {
this code must be from branching off of my earlier branch, I would say that it is not ready to be merged yet but i know that there are 6 other PRs active and some of the other developers have been refactoring this code. considering the time frame we're working with, I think we should merge this in.

2018-11-02 00:44 UTC, danvanhorn commented on src/clients/search/search.spec.ts
> +describe('search client', () => {
Once again, obviously incomplete but in the interest of time we should go with this.

2018-11-02 00:54 UTC, danvanhorn requested changes
I don't know what tasks are associated with this PR, I assume it is CSE-68 or CSE-307, which are duplicate tasks concerned with "implementing home page design". There is another task, CSE-71, which is about connecting the home buttons to the relevant pages. From reading that task description and cross-referencing it with the code, I don't think this is implemented. I need more information about the related task numbers and a description of the changes if I'm going to be able to review this properly.

2018-11-05 20:00 UTC, merged

2018-11-09 01:05 UTC, cass-osu commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/osu-cass/AP-CSE-APP/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: