fix(format-content): remove backslash & parse char ref
osu-cass/AP-CSE-APP pull request #99
Opened 2018-12-20 22:10 UTC by iglenwoo

# Changes introduced

I have removed backslash and parsed character references in target content.

## Related issue(s):

- [CSE-348](https://sbacjira.atlassian.net/browse/CSE-348)

## Contributor checklist

- [ ] Wrote/updated tests for introduced changes
- [ ] Added new stories for created/modified components (if applicable)
- [ ] Checked Storybook for Accessibility issues (if applicable)
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [ ] Verified that there are no issues in CircleCI
- [ ] Assigned yourself to the PR
- [ ] Removed `WIP:` from the PR title
- [ ] Requested review from the SB Reviewers team

## Reviewer checklist

- [ ] Assigned yourself to the PR
- [ ] Read through the changes in the `Files changed` tab
- [ ] Verified that tests were written/modified
- [ ] Verified that stories were written/modified (if applicable)
- [ ] ~~Verified that Postman was updated (if applicable)~~
- [ ] Checked out the branch and tested changes locally
- [ ] Run storybook and checked that there are no accessibility issues

2018-12-20 22:29 UTC, puregarlic requested changes
Just a couple of changes necessary.

2018-12-20 22:29 UTC, puregarlic commented on src/components/MainContent/parseUtils.tsx
> +  parsers.map((parser: (text: string) => string) => {
`map` returns a new array when it completes. If you merely want to iterate over the array and execute a function on each item, use `foreach` instead.
```suggestion
  parsers.forEach((parser: (text: string) => string) => {
```

2018-12-20 22:29 UTC, puregarlic commented on src/components/MainContent/parseUtils.tsx
> +const parsersInOrder = [replaceDashWithDot, removeBackSlash, replaceCharRef];
A comment explaining why the parsers need to be in this order would be appreciated.

2018-12-20 22:29 UTC, puregarlic commented on src/components/MainContent/parseUtils.tsx
> +const applyParsers = (parsers: ((text: string) => string)[], text: string) => {
I'd like to soapbox for just a second to say that the [pipeline operator proposal](https://github.com/tc39/proposal-pipeline-operator) would make this solution a heck of a lot cleaner, but, alas, this will do.

2018-12-20 22:44 UTC, iglenwoo commented on src/components/MainContent/parseUtils.tsx
> +const parsersInOrder = [replaceDashWithDot, removeBackSlash, replaceCharRef];
I renamed the variable since there is no reason to run parsers in order.

2018-12-20 22:45 UTC, iglenwoo commented on src/components/MainContent/parseUtils.tsx
> +  parsers.map((parser: (text: string) => string) => {
I changed it from map to forEach. Thank you for the clear explanation.

2018-12-20 22:45 UTC, iglenwoo commented on src/components/MainContent/parseUtils.tsx
> +const applyParsers = (parsers: ((text: string) => string)[], text: string) => {
That's cool! Thank you for the information.

2018-12-20 23:39 UTC, puregarlic approved these changes
Awesome, nice work.

2018-12-21 00:11 UTC, merged

2018-12-21 00:12 UTC, cass-osu commented
:tada: This PR is included in version 1.23.6 :tada:

The release is available on [GitHub release](https://github.com/osu-cass/AP-CSE-APP/releases/tag/v1.23.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: